In [1]:
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests
import re

In [2]:
vacancies = []
vacancy_input = input('Введите название вакансии: ')
pages_input = input('Введите количество анализируемых страниц: ')

Введите название вакансии: Python
Введите количество анализируемых страниц: 5

In [3]:
for page in range(int(pages_input)):
    link = 'https://hh.ru/search/vacancy'
   
  
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
    response = requests.get(f'{link}?clusters=true&area=88&ored_clusters=true&enable_snippets=' \
                  f'true&salary=&st=searchVacancy&text={vacancy_input}&page=0', headers=headers)

    # Парсинг страницы
    soup = bs(response.content, 'html.parser')
    vacancy_list = soup.find_all('div', {'class': 'vacancy-serp-item'})

    for vacancy in vacancy_list:
        vacancy_data = {}
        vacancy_link = vacancy.find('a', attrs={'class': 'bloko-link'})['href']
        vacancy_name = vacancy.find('div', {'class': 'vacancy-serp-item__info'}).find('a').getText()
        try:
            vacancy_salary = vacancy.find('div', {'class': 'vacancy-serp-item__sidebar'}).getText()
       
        
            vacancy_salary_list = vacancy_salary.split( )
            if len(vacancy_salary) > 1:
                if vacancy_salary_list[0] == 'от':
                    vacancy_data['salary_min'] = int(vacancy_salary_list[1] + vacancy_salary_list[2])
                    vacancy_data['salary_max'] = 'NaN'
                    vacancy_data['currency'] = vacancy_salary_list[3]
                elif vacancy_salary_list[0] == 'до':
                    vacancy_data['salary_min'] = 'NaN'
                    vacancy_data['salary_max'] = int(vacancy_salary_list[1] + vacancy_salary_list[2])
                    vacancy_data['currency'] = vacancy_salary_list[3]
                elif vacancy_salary.find('-') & len(vacancy_salary) > 3:
                    vacancy_data['salary_min'] = int(vacancy_salary_list[0] + vacancy_salary_list[1][:3])
                    vacancy_data['salary_max'] = int(vacancy_salary_list[3] + vacancy_salary_list[1][:3])
                    vacancy_data['currency'] = vacancy_salary_list[-1]
            else:
                vacancy_data['salary_min'] = 'NaN'
                vacancy_data['salary_max'] = 'NaN'
                vacancy_data['currency'] = 'NaN'
        except:
            vacancy_salary = 'No salary'
        
       
        vacancy_company = vacancy.find('div', {'class': 'vacancy-serp-item__meta-info'}).find('a').getText()
    
        vacacy_city = vacancy.find('span', {'class': 'vacancy-serp-item__meta-info'}).string

        vacancy_data['name'] = vacancy_name
        vacancy_data['link'] = vacancy_link
        vacancy_data['company'] = vacancy_company
        #vacancy_data['salary_min'] = salary_min
        #vacancy_data['salary_max'] = salary_max
        vacancy_data['city'] = vacacy_city
        vacancy_data['site'] = 'hh.ru'
    


        vacancies.append(vacancy_data)
df_vacancies = pd.DataFrame(vacancies)
df_vacancies.to_csv(f'df_vacancies_hh_{vacancy_input}.csv', encoding='utf-8')

In [4]:
df_vacancies

,salary_min,salary_max,currency,name,link,company,city,site
0,90000,250000,руб.,Веб-программист Python middle,https://arkhangelsk.hh.ru/vacancy/48345716?fro...,Комиссаров Павел,Казань,hh.ru
1,150000,200000,руб.,"Python Django разработчик, удаленно",https://arkhangelsk.hh.ru/vacancy/48522330?fro...,эдмин,Казань,hh.ru
2,NaN,NaN,NaN,Middle/Senior Python-разработчик в команду Доб...,https://arkhangelsk.hh.ru/vacancy/47616458?fro...,2ГИС,Казань,hh.ru
3,150000,200000,руб.,Python разработчик (Казань),https://arkhangelsk.hh.ru/vacancy/48083887?fro...,ООО Ракета,Казань,hh.ru
4,150000,NaN,руб.,Middle Backend Python + Django разработчик,https://arkhangelsk.hh.ru/vacancy/48651118?fro...,KiteGroup,Казань,hh.ru
...,...,...,...,...,...,...,...,...
95,NaN,200000,руб.,Программист Python,https://arkhangelsk.hh.ru/vacancy/47717493?fro...,INNOVA GROUP,None,hh.ru
96,NaN,NaN,NaN,Python-разработчик в команду Data Science,https://arkhangelsk.hh.ru/vacancy/47706465?fro...,2ГИС,Казань,hh.ru
97,NaN,NaN,NaN,Python Developer/DevOps,https://arkhangelsk.hh.ru/vacancy/48479693?fro...,Playrix,Казань,hh.ru
98,NaN,NaN,NaN,Python Developer (Flask),https://arkhangelsk.hh.ru/vacancy/47739383?fro...,Nitka Technologies,Казань,hh.ru
99,NaN,NaN,NaN,Backend Python Developer,https://arkhangelsk.hh.ru/vacancy/39266383?fro...,ООО UMA.Tech,Казань,hh.ru

In [5]:
]

SyntaxError: unmatched ']' (<ipython-input-5-86032d473a68>, line 1)